Side branch1
akshatagrawal4590/NVD pull request #1
Opened 2023-05-25 13:34 UTC by akshatagrawal4590

Connection made successfully.

2023-05-31 11:57 UTC, shivasarvaha commented
hi

2023-05-31 11:59 UTC, shivasarvaha requested changes

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +    } else {
put return statement when you send the response. It is not needed but it improve code readability

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +
remove unnecessary spaces.

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +    if(documents1.length === 0 && documents2.length === 0)
this should be 
`if () {`

follow one of the formating or you can add linter to enforce formating

2023-05-31 11:59 UTC, shivasarvaha commented on mongo_connect.js
> +    db = res.db(db_name);
db not declared previously

2023-05-31 11:59 UTC, shivasarvaha commented on mongo_connect.js
> +    db = res.db(db_name);
this will be added in global scope which is not recommended practice

2023-05-31 11:59 UTC, shivasarvaha commented on mongo_connect.js
> +const dbConnectHardwareCPE = function() {
rather than writing all 3 functions dbConnectHardwareCPE,  dbConnectSoftwareCPE, dbConnectCVE we can add a simple getCollection function as 
```
const getCollection = function(collection) {
  return db.collection('collection);
};
```

Saves repetitive code

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +    const documents1 = await collection1.find({vendor: req.params.cpeVendor}).toArray();
we need to search using the name for software and model for hardware check in the respective CPE collections

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +    if(documents1.length === 0 && documents2.length === 0)
also the check can be` !documents.length ` rather than comparing to 0

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +      res.json(combinedData);
```
res.json ({
        hardware_CPEs: documents1,
        software_CPEs: documents2
})
```

this can be done rather than creating a new variable

2023-05-31 11:59 UTC, shivasarvaha commented on app.js
> +    console.log(error);
return the respective error response to user else if we get error user will not get any response on API

2023-05-31 11:59 UTC, shivasarvaha commented on mongo_connect.js
> +  const url = "mongodb://0.0.0.0:27017/mdm";
get all DB urls, ports from environment variables

2023-06-04 19:21 UTC, akshatagrawal4590 commented on mongo_connect.js
> +    db = res.db(db_name);
I have declared it now. So global scope problem will not be there.

2023-06-04 19:38 UTC, akshatagrawal4590 commented on mongo_connect.js
> +  const url = "mongodb://0.0.0.0:27017/mdm";
I have added environment variables.

2023-06-04 19:39 UTC, akshatagrawal4590 commented on app.js
> +
Done.

2023-06-04 19:44 UTC, akshatagrawal4590 commented on app.js
> +    console.log(error);
Now the error is also returned to the user.

2023-06-04 19:44 UTC, akshatagrawal4590 commented on app.js
> +      res.json(combinedData);
Done.

2023-06-05 07:29 UTC, akshatagrawal4590 commented on app.js
> +    const documents1 = await collection1.find({vendor: req.params.cpeVendor}).toArray();
Resolved.

2023-07-20 06:57 UTC, merged